### ISSUE TITLE
התרעות=התראות

### ISSUE THREAD

**Issue by ophirberen** [ingbrzy/MIUI-XML-V8-HEBREW#1]
The word התרעות is mispelled in clock. The correct spelling is התראות

**Comment by IgorEisberg** [comment]
ממש לא.
התראות = notifications
התרעות = alarms
הכל תקין.

**Comment by ophirberen** [comment]
לצערי לא. קבל ציטוט:
"בעברית בת ימינו התפתחה משמעות נוספת למילה התראה: 'הודעה (מוקדמת)', כגון 'הם הגיעו לביקור בלי התראה (מוקדמת)'. שימוש זה נפוץ בלשון הצבאית: התראה היא הודעה על פעולה צפויה הנמסרת מבעוד מועד כדי לאפשר להיערך לקראתה. בדיון באקדמיה על השימוש בהתראה במשמעות 'הודעה מוקדמת' הוסכם שאין טעם לפסול שימוש זה, ועם זאת מוטב לנקוט 'הודעה מוקדמת'.

**הרתעה** וכן הפועל **הרתיע** משמעם **איום** על צד אחר כדי שיירתע ויימנע מלעשות פעולה כלשהי. לדוגמה: 'נשק גרעיני מרתיע מפני התקפה'; 'קנסות גבוהים אולי ירתיעו נהגים עבריינים'.

נלקח מפה:http://hebrew-academy.org.il/2010/10/14/%D7%94%D7%AA%D7%A8%D7%A2%D7%94-%D7%94%D7%AA%D7%A8%D7%90%D7%94-%D7%94%D7%A8%D7%AA%D7%A2%D7%94/

שימוש בהתרעה מתכוון לאיום המתרחש לבוא, לרוב שלילי ולא קשור להודעה עתידית או נוטיפיקיישן (התרגום בעברית הוא "הודעה" או "הודעה בדחיפה" לפי האקדמיה ללשון. )

**Comment by IgorEisberg** [comment]
לא מבין מה קשור ל"הרתעה" בכלל. הרתעה והתרעה אלו שתי מילים שונות. בכל מקרה, זאת ההחלטה.

**Comment by ophirberen** [comment]
הרתעה והתרעה שייכים לאותו הפועל ומשם ההקשר.
את ההחלטה אתה עשית, והיא לא מדוייקת לשפה העברית.
אין היום אף מכשיר בעברית שמשתמש במילה התרעה לשעון מעורר.

בנוסף, אני לא מבין למה אתה עונה בכזאת תוקפנות, חלק מהעניין בקוד פתוח ושיתוף היא לקבל את התרומה של כולם לפרויקט.

 אני מעריך מאוד את התרומה שלך, אכן אין טעויות והתרגום מושלם, למעט טעות אחת קטנה ולכן אין צורך להתעצבן וגם אם תחליט שלא לשנות, הכל טוב אחי.
אבל לא צריך לקחת את הדברים שלי בתור ביקורת, סך הכל מנסה לדייק.

לילה טוב,
תודה על הכל!

**Comment by IgorEisberg** [comment]
שיניתי, אם זה כל כך מפריע לך... אני לא משתמש בעברית בכל מקרה.
