### ISSUE TITLE
When sending SMS in Hebrew, the recipient receives an empty message

### ISSUE THREAD

**Issue by xiaomisrael1** [ingbrzy/MIUI-XML-V8-HEBREW#6]
There is also a problem with this version. When sending SMS in Hebrew, the recipient receives an empty message. Please fix it. The problem also exists in the previous version.

עדכנתי את הגרסה הקודמת וגם את החדשה ביותר. בשניהם שמתי לב כי ההודעות שמקבל הנמען ממני, מגיעות אליו ריקות.

ביצעתי מספר בדיקות מול אחרים והסתבר לי בדיעבד שהתקלה אצלי בוודאות מאחר וכאשר אני שולח טקסט באנגלית, הוא כן מגיע. 

הבעיה היא בשליחת טקסט בעברית באמצעות סמס. כאשר אני שולח בוואטצפ הכל תקין.
ניסיתי אפילו להחליף מקלדת אבל זה לא עזר. המשמעות היא שהתקלה היא בוודאות בגרסה הזו ובזו הקודמת.

אשמח לעזרתכם בנושא.

**Comment by ingbrzy** [comment]
Not a translation issue..

Enable/Disable GSM alphabet in SMS settings...

**Comment by xiaomisrael1** [comment]
I did it. Despite everything, it did not help.

**Comment by xiaomisrael1** [comment]
I'd love to know, what's the right way?

**Comment by kkffiirr** [comment]
שבוע טוב. 

לך להודעות, החזק מקש שמאלי כדי להגיע להגדרות. 
רד עד למטה ובטל את "השתמש באלפאבית של GSM"

**Comment by xiaomisrael1** [comment]
שבוע טוב,

תודה רבה! עזרת לי מאוד!

בתאריך 22 באפר׳ 2017 20:46,‏ "kkffiirr" <notifications@github.com> כתב:

**Comment by kkffiirr** [comment]
Glad to hear that it's working for you. 
Spread the word.

**Comment by Opi-B** [comment]
תודה רבה :)
