### ISSUE TITLE
תרגום ל CHARGING MONITOR

### ISSUE THREAD

**Issue by Yoni1581** [ingbrzy/MIUI-XML-V8-HEBREW#8]
שלום,
אני עם MI5
כרגע בגרסא האחרונה 7.5.25
והוסיפו משהו חדש 
את ה CHARGING MONITOR
אשמח שתתרגמו את זה כי זה נמצא במסך הנעילה וזה מאוד מעצבן לראות אנגלית וסינית כל פעם שאני מדליק את המסך

**Comment by kkffiirr** [comment]
מרוצה?

**Comment by kkffiirr** [comment]
מרוצה?

**Comment by Yoni1581** [comment]
כן!! תודה רבה!!!!

**Comment by kkffiirr** [comment]
Ingbrzy, it is now resolved
